apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: lothairdocker/python-app:1.0.3
        volumeMounts:
        - mountPath: /python-app
          name: python-app-volume
      volumes:
        - name: python-app-volume
          hostPath:
            path: /python-app
